import axios from "axios";
import { NextPage } from "next";
import Head from "next/head";
import React, { useEffect } from "react";
import { useCookies } from "react-cookie";

import { Layout } from "../../components/layout";
import ProductCard from "../../components/productcard";
import Product from "../../interfaces/product.interface";
import { parseCookies } from "../../servcies/cookie.helper";
import { GTMService } from "../../servcies/gtm.service";
import { MixpanelTracking } from "../../servcies/mixpanel";

interface Props {
  product: Product;
}

const ProductDetail: NextPage<Props> = ({ product }) => {
  const [cookies] = useCookies();
  useEffect(() => {
    MixpanelTracking.getInstance().productViewed(product);
  }, []);
  const handleAddToCart = () => {
    MixpanelTracking.getInstance().addedToCart(product);
    GTMService.getInstance().productAddedToCart(product, parseCookies(cookies));
  };
  return (
    <Layout>
      <Head>
        <title>{product.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-6">
        <ProductCard product={product} />
      </div>
      <div>
        <button
          className="p-3 bg-green-700 rounded text-white"
          onClick={handleAddToCart}
        >
          Add to Cart
        </button>
      </div>
    </Layout>
  );
};

export default ProductDetail;

export async function getServerSideProps(context: any): Promise<{ props: {} }> {
  const resp = await axios.get(
    `${process.env.API}/products/${context.params.slug}`
  );
  return {
    props: {
      product: resp.data,
    },
  };
}
