import axios from "axios";
import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import React, { useEffect } from "react";
import { useCookies } from "react-cookie";

import { Layout } from "../../components/layout";
import ProductCard from "../../components/productcard";
import TrackingEvents from "../../enums/tracking-events.enum";
import Product from "../../interfaces/product.interface";
import ProductsPaginated from "../../interfaces/products-paginated.interface";
import { parseCookies } from "../../servcies/cookie.helper";
import { GTMService } from "../../servcies/gtm.service";
import { MixpanelTracking } from "../../servcies/mixpanel";

interface Props {
  products: ProductsPaginated;
}

const Products: NextPage<Props> = ({ products }) => {
  const [cookies, setCookies] = useCookies();
  useEffect(() => {
    MixpanelTracking.getInstance().track(TrackingEvents.PAGE_VIEW);
  }, []);
  const productView = (product: Product) => {
    GTMService.getInstance().productViewed(product);
  };
  return (
    <Layout>
      <Head>
        <title>The Market products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-cols-2 gap-16">
        {products.data.length > 0 &&
          products.data.map((product: Product) => {
            return (
              <div key={product.id}>
                <Link href={`/products/${product.slug}`}>
                  <a
                    className="cursor-pointer"
                    onClick={() => productView(product)}
                  >
                    <ProductCard product={product} />
                  </a>
                </Link>
              </div>
            );
          })}
      </main>
    </Layout>
  );
};
export default Products;

export async function getServerSideProps(context: any): Promise<{ props: {} }> {
  const resp = await axios.get(`${process.env.API}/products`);
  return {
    props: {
      products: resp.data,
    },
  };
}
