import axios from "axios";
import { Formik, FormikHelpers } from "formik";
import Head from "next/head";
import Router from "next/router";
import { useCookies } from "react-cookie";

import { Layout } from "../components/layout";
import { GTMService } from "../servcies/gtm.service";

import type { NextPage } from "next";
const Home: NextPage = () => {
  const [cookie, setCookie] = useCookies();
  const handleLogin = async (
    values: any,
    formikHelpers: FormikHelpers<any>
  ) => {
    const { email, password } = values;
    const resp = await axios.post("/api/login", {
      email,
      password,
    });
    setCookie("auth_token", JSON.stringify(resp.data.token), {
      path: "/",
      maxAge: 3600, // Expires after 1hr
      sameSite: true,
    });
    setCookie("userId", JSON.stringify(resp.data.userId), {
      path: "/",
      maxAge: 3600, // Expires after 1hr
      sameSite: true,
    });
    GTMService.getInstance().userLoggedIn(resp.data.userId);
    Router.push("/products");
  };
  return (
    <Layout>
      <Head>
        <title>Login - The Market Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container">
          <Formik
            initialValues={{
              email: "",
              password: "",
            }}
            onSubmit={handleLogin}
          >
            {({ values, handleSubmit, handleChange }) => (
              <div className="shadow rounded border-2 p-6 w-2/4 mx-auto mt-6">
                <form onSubmit={handleSubmit}>
                  <input
                    className="rounded border-2 p-2 border-gray-700 w-full mb-4"
                    type="email"
                    name="email"
                    onChange={handleChange}
                    value={values.email}
                    placeholder="Enter your email"
                  />

                  <input
                    className="rounded border-2 p-2 border-gray-700 w-full mb-4"
                    type="password"
                    name="password"
                    onChange={handleChange}
                    value={values.password}
                    placeholder="Enter your password"
                  />

                  <button className="rounded px-4 py-2 bg-green-800 w-full text-white">
                    Login
                  </button>
                </form>
              </div>
            )}
          </Formik>
        </div>
      </main>
    </Layout>
  );
};

export default Home;
